### PR TITLE
Second QoL 

### PR DESCRIPTION
**Pull request by SomeoneWeird**
This resets `tsconfig.json` to require a bunch more rules, mainly around checking for `undefined` and `null` values.

I have tried not to change business logic anywhere, although there was a couple places that needed rewriting in a typescript-safe manner. Most other changes are just setting default values etc.

This is completely untested other than for me joining a lobby, but things seem to work.

### CODE REVIEW

**Review by roobscoob — COMMENTED** [review]
Why was port moved from server.listen() to the server construction config?

**Comment by SomeoneWeird** [comment]
I did this for some specific reason before you introduced the server config object in your latest commit. Does it not make sense to have the port specified in the config object you pass in when instantiating a server?

**Review by roobscoob — CHANGES_REQUESTED** [review]
This breaks DisconnectReasons. We can't create a disconnect reason of -1, and the default disconnect reason can be used sometimes. If DisconnectReason is called without a packet, it's an empty DisconnectReason which is a valid DisconnectReason.

**Comment by roobscoob** [comment]
> I did this for some specific reason before you introduced the server config object in your latest commit. Does it not make sense to have the port specified in the config object you pass in when instantiating a server?

I feel in most cases it would but for *port* specifically not really, as the port is more of a parameter to listen() than it is to a server. Down to take others opinions but I'm pretty sure it should be in listen

**Comment by SomeoneWeird** [comment]
> This breaks DisconnectReasons. We can't create a disconnect reason of -1, and the default disconnect reason can be used sometimes. If DisconnectReason is called without a packet, it's an empty DisconnectReason which is a valid DisconnectReason.

Fixed


> > I did this for some specific reason before you introduced the server config object in your latest commit. Does it not make sense to have the port specified in the config object you pass in when instantiating a server?
> 
> I feel in most cases it would but for _port_ specifically not really, as the port is more of a parameter to listen() than it is to a server. Down to take others opinions but I'm pretty sure it should be in listen

It would make sense if we weren't already passing in configuration when instantiating a server object, but the port a server should listen on is most absolutely a configuration parameter, and if we leave that out and only require it on a `listen()` call that makes the API quite confusing IMO

**Review by roobscoob — CHANGES_REQUESTED** [review]
The parse and serialize functions on Component.ts should *not* take a room. Room should be a property set in the constructor of the component

**Comment by roobscoob** [comment]
> > > I did this for some specific reason before you introduced the server config object in your latest commit. Does it not make sense to have the port specified in the config object you pass in when instantiating a server?
> > 
> > 
> > I feel in most cases it would but for _port_ specifically not really, as the port is more of a parameter to listen() than it is to a server. Down to take others opinions but I'm pretty sure it should be in listen
> 
> It would make sense if we weren't already passing in configuration when instantiating a server object, but the port a server should listen on is most absolutely a configuration parameter, and if we leave that out and only require it on a `listen()` call that makes the API quite confusing IMO

@Sanae6 can we get your opinion on this? What do you think

**Comment by SomeoneWeird** [comment]
> The parse and serialize functions on Component.ts should _not_ take a room. Room should be a property set in the constructor of the component

Can I ask why not?

**Review by roobscoob — CHANGES_REQUESTED** [review]
looking through this again, many classes put the room in the parse function. I don't think I'm for this as room is less of a _parameter_ to parse and more of inherent stateful data that parse uses

**Comment by SomeoneWeird** [comment]
Yes, this is because the next step is to actually get rid of classes like in PR #9 and have things completely stateless, as that makes things much simpler and more explicit, as the current API has `room` optional in a lot of these.

**Comment by SomeoneWeird** [comment]
Having the packet handlers completely stateless also means adding tests is a lot easier as well - you don't require an instance of the thing, and they're deterministic from the get-go :)

**Pull request merged**
