### PR TITLE
Add mocha and chai for unit tests

### PR DESCRIPTION
**Pull request by asecondo**
There are currently no real unit tests for any of the modules in this repository.  Mocha and Chai were chosen somewhat arbitrarily, but they appear to to have the required functionality to write the basic unit tests that this repository needs.

Most of the changes made in this PR were mechanical, as the previous imports were importing the JavaScript file itself, instead of the exported module/class.

All of the changes in this PR are very much up for debate, as this will define the unit test structure that will be used for future unit tests that must be written to ensure that bugs are not introduced as the code base evolves.

### CODE REVIEW

**Comment by edqx** [comment]
What's wrong with the `.js` imports? I use ts-node and it doesn't work unless the `.js` imports are there.

**Comment by asecondo** [comment]
> What's wrong with the `.js` imports? I use ts-node and it doesn't work unless the `.js` imports are there.

In the example Component unit test, I was running into issues with module dependencies that were imported in `Component.ts`. When specific file imports are used, errors would occur when running `npm test`.  For example, if I change the `PolusBuffer` input to instead be `PolusBuffer.js`, you'll see these types of errors:

Error: Cannot find module '../../util/PolusBuffer.js'
Require stack:
- C:\Users\Tony\git-repos\NodePolus\lib\packets\PacketElements\Component.ts
- C:\Users\Tony\git-repos\NodePolus\tests\lib\packets\PacketElements\Component.test.ts
- C:\Users\Tony\git-repos\NodePolus\node_modules\mocha\lib\esm-utils.js
- C:\Users\Tony\git-repos\NodePolus\node_modules\mocha\lib\mocha.js
- C:\Users\Tony\git-repos\NodePolus\node_modules\mocha\lib\cli\one-and-dones.js
- C:\Users\Tony\git-repos\NodePolus\node_modules\mocha\lib\cli\options.js
- C:\Users\Tony\git-repos\NodePolus\node_modules\mocha\bin\mocha

Although I'm new to TypeScript, it seems that the best practices suggest not using the `.js` file imports anyway.  See the `Import a module for side-effects only` section here: https://www.typescriptlang.org/docs/handbook/modules.html#:~:text=In%20TypeScript%2C%20just%20as%20in,therefore%20to%20modules%20as%20well).

**Comment by SomeoneWeird** [comment]
Yeah, if your files are typescript you should be importing by name only, that way depending on if they're run pre-transpile or not it will still function. 

In regards to testing, I'm a huge fan of `ava` instead of `mocha` because fo its built-in typescript support, and additionally just using nodes built-in `assert` library for actual testing, rather than `chai`. Certainly not going to dictate any of that though.

**Comment by asecondo** [comment]
I'll take a look into `ava` to see how it looks.  I prefer unit testing frameworks with a great DSL like https://www.scalatest.org/ but obviously those are language specific.

**Comment by roobscoob** [comment]
We tried without extensions, didn't work file not found. The only solution was to .js them

**Comment by SomeoneWeird** [comment]
Thanks for your PR, I've decided to go with ava because of better TS support and much nicer testing output than mocha :)

**Pull request closed without merging**
